version: '3.7'

services:
  api:
    image: eminevimdockertest/api:v1
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 5s
        order: stop-first
    ports:
      - "51331:51331"
    networks: 
      - eminnetwork    
  app:
    image: eminevimdockertest/app:v1
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 5s
        order: stop-first
    ports:
      - "43093:43093"
    networks: 
      - eminnetwork    

networks:
  eminnetwork:
    driver: overlay

